package ollama

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// testServer spins up a fake Ollama and returns a client pointed at it.
func testServer(t *testing.T, h http.Handler) (*Client, *httptest.Server) {
	t.Helper()
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)
	return New(srv.URL, ""), srv
}

const tagsBody = `{
  "models": [
    {
      "name": "qwen3:8b",
      "model": "qwen3:8b",
      "modified_at": "2026-09-03T08:00:00.123456789Z",
      "size": 5150000000,
      "digest": "sha256:abc",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "qwen3",
        "families": ["qwen3"],
        "parameter_size": "8.2B",
        "quantization_level": "Q4_K_M"
      }
    },
    {
      "name": "gemma3:12b",
      "model": "gemma3:12b",
      "modified_at": "2026-08-01T01:02:03Z",
      "size": 8123456789,
      "digest": "sha256:def",
      "details": {
        "parent_model": "gemma3:4b",
        "format": "gguf",
        "family": "gemma3",
        "families": ["gemma3"],
        "parameter_size": "12B",
        "quantization_level": "Q4_K_M"
      }
    }
  ]
}`

func TestListParsesModels(t *testing.T) {
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/api/tags" {
			// Stray localhost prober traffic gets a silent 404, never a test
			// error; a real client mistake still fails via the client's own
			// error (phase-5 LEDGER note).
			w.WriteHeader(404)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(tagsBody))
	}))

	models, err := c.List(context.Background())
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(models) != 2 {
		t.Fatalf("len = %d, want 2", len(models))
	}

	q := models[0]
	if q.Name != "qwen3:8b" || q.Family != "qwen3" ||
		q.ParameterSize != "8.2B" || q.Quantization != "Q4_K_M" ||
		q.SizeBytes != 5150000000 {
		t.Errorf("unexpected first model: %+v", q)
	}
	wantMod := time.Date(2026, 9, 3, 8, 0, 0, 123456789, time.UTC)
	if !q.ModifiedAt.Equal(wantMod) {
		t.Errorf("ModifiedAt = %v, want %v", q.ModifiedAt, wantMod)
	}

	g := models[1]
	if g.Family != "gemma3" || g.ParameterSize != "12B" {
		t.Errorf("unexpected second model: %+v", g)
	}
}

func TestListSendsBearerToken(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/api/tags" {
			w.WriteHeader(404)
			return
		}
		gotAuth = r.Header.Get("Authorization")
		w.Write([]byte(`{"models":[]}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "sekrit")
	if _, err := c.List(context.Background()); err != nil {
		t.Fatalf("List: %v", err)
	}
	if gotAuth != "Bearer sekrit" {
		t.Errorf("Authorization = %q, want %q", gotAuth, "Bearer sekrit")
	}
}

func TestListNoTokenNoHeader(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/api/tags" {
			w.WriteHeader(404)
			return
		}
		gotAuth = r.Header.Get("Authorization")
		w.Write([]byte(`{"models":[]}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	if _, err := c.List(context.Background()); err != nil {
		t.Fatalf("List: %v", err)
	}
	if gotAuth != "" {
		t.Errorf("Authorization = %q, want empty", gotAuth)
	}
}

const showBody = `{
  "license": "Apache-2.0",
  "modelfile": "# Modelfile generated by ollama show\nFROM qwen3:8b",
  "parameters": "stop \"<|im_end|>\"\ntemperature 0.7",
  "template": "{{ .Prompt }}",
  "details": {
    "parent_model": "",
    "format": "gguf",
    "family": "qwen3",
    "families": ["qwen3"],
    "parameter_size": "8.2B",
    "quantization_level": "Q4_K_M"
  },
  "model_info": {
    "general.architecture": "qwen3",
    "general.parameter_count": 8240000000,
    "general.file_type": 15
  },
  "projector_info": {},
  "capabilities": ["completion", "tools"]
}`

func TestShowPostsNameAndParses(t *testing.T) {
	var gotBody string
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/api/show" {
			w.WriteHeader(404)
			return
		}
		var req map[string]string
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			t.Errorf("decode request: %v", err)
		}
		gotBody = req["name"]
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(showBody))
	}))

	d, err := c.Show(context.Background(), "qwen3:8b")
	if err != nil {
		t.Fatalf("Show: %v", err)
	}
	if gotBody != "qwen3:8b" {
		t.Errorf("request name = %q, want qwen3:8b", gotBody)
	}
	if d.License != "Apache-2.0" || d.Details.ParameterSize != "8.2B" {
		t.Errorf("unexpected details: %+v", d)
	}
	if len(d.Capabilities) != 2 || d.Capabilities[0] != "completion" {
		t.Errorf("capabilities = %v", d.Capabilities)
	}
	count, ok := d.ModelInfo["general.parameter_count"].(float64)
	if !ok || count != 8240000000 {
		t.Errorf("model_info.parameter_count = %v, want 8240000000", d.ModelInfo["general.parameter_count"])
	}
	if !strings.Contains(d.Modelfile, "FROM qwen3:8b") {
		t.Errorf("modelfile = %q", d.Modelfile)
	}
}

func TestShowEmptyNameRejected(t *testing.T) {
	c := New("http://localhost:11434", "")
	if _, err := c.Show(context.Background(), ""); err == nil {
		t.Fatal("Show with empty name: want error, got nil")
	}
}

func TestAPIErrorBodySurfaced(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(`{"error":"model 'nothere' not found"}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	_, err := c.Show(context.Background(), "nothere")
	if err == nil {
		t.Fatal("want error, got nil")
	}
	if !strings.Contains(err.Error(), "model 'nothere' not found") {
		t.Errorf("error = %v, want surfaced API message", err)
	}
}

func TestHTTPStatusWithoutJSONError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte("Not Found"))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	if _, err := c.List(context.Background()); err == nil {
		t.Fatal("want error, got nil")
	} else if !strings.Contains(err.Error(), "404") {
		t.Errorf("error = %v, want HTTP status in message", err)
	}
}

func TestConnectionRefused(t *testing.T) {
	// A closed listener gives a guaranteed-refused address.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	addr := srv.URL
	srv.Close()

	c := New(addr, "")
	if _, err := c.List(context.Background()); err == nil {
		t.Fatal("want error for refused connection, got nil")
	}
}

func TestRequestTimeout(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(200 * time.Millisecond)
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	c.http.Timeout = 20 * time.Millisecond
	start := time.Now()
	if _, err := c.List(context.Background()); err == nil {
		t.Fatal("want timeout error, got nil")
	}
	if time.Since(start) > 250*time.Millisecond {
		t.Errorf("timeout took %v, want fast failure", time.Since(start))
	}
}

func TestContextCancelled(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		<-r.Context().Done()
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := c.List(ctx); err == nil {
		t.Fatal("want cancelled-context error, got nil")
	}
}

func TestHostTrailingSlashNormalized(t *testing.T) {
	var path string
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/api/tags" {
			w.WriteHeader(404)
			return
		}
		path = r.URL.Path
		w.Write([]byte(`{"models":[]}`))
	}))
	// Point a second client at the same host with trailing slashes.
	c2 := New(c.baseURL+"/", "")
	if _, err := c2.List(context.Background()); err != nil {
		t.Fatalf("List: %v", err)
	}
	if path != "/api/tags" {
		t.Errorf("path = %q, want /api/tags (no double slash)", path)
	}
}

// --- M1b: DELETE + streaming pull -------------------------------------------

func TestDeletePostsName(t *testing.T) {
	got := struct{ method, path, name string }{}
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete || r.URL.Path != "/api/delete" {
			w.WriteHeader(404)
			return
		}
		got.method, got.path = r.Method, r.URL.Path
		var req struct{ Name string }
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			t.Errorf("decode request: %v", err)
		}
		got.name = req.Name
		w.Write([]byte(`{"status":"success"}`))
	}))

	if err := c.Delete(context.Background(), "qwen3:8b"); err != nil {
		t.Fatalf("Delete: %v", err)
	}
	if got.method != http.MethodDelete || got.path != "/api/delete" {
		t.Errorf("got %s %s, want DELETE /api/delete", got.method, got.path)
	}
	if got.name != "qwen3:8b" {
		t.Errorf("request name = %q, want qwen3:8b", got.name)
	}
}

func TestDeleteErrorSurfaced(t *testing.T) {
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"error":"model 'nope' not found"}`))
	}))

	err := c.Delete(context.Background(), "nope")
	if err == nil {
		t.Fatal("want error, got nil")
	}
	if !strings.Contains(err.Error(), "model 'nope' not found") {
		t.Errorf("error = %v, want surfaced API message", err)
	}
}

func TestDeleteEmptyNameRejected(t *testing.T) {
	c := New("http://localhost:11434", "")
	if err := c.Delete(context.Background(), ""); err == nil {
		t.Fatal("Delete with empty name: want error, got nil")
	}
}

// pullStream mirrors a real POST /api/pull NDJSON response: manifest phase,
// one layer with progress, final verification/write, success.
const pullStream = `{"status":"pulling manifest"}
` +
	`{"status":"pulling 7f4030143c1c","digest":"sha256:7f4030143c1c477224c5434f8272c662a8b042079a0a584f0a27a1684fe2e1fa","total":522640096,"completed":0}
` +
	`{"status":"pulling 7f4030143c1c","digest":"sha256:7f4030143c1c477224c5434f8272c662a8b042079a0a584f0a27a1684fe2e1fa","total":522640096,"completed":522640096}
` +
	`{"status":"verifying sha256 digest"}
` +
	`{"status":"writing manifest"}
` +
	`{"status":"success"}
`

func TestPullStreamsProgress(t *testing.T) {
	got := struct {
		name   string
		stream bool
	}{}
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/api/pull" {
			w.WriteHeader(404)
			return
		}
		var req map[string]any
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			t.Errorf("decode request: %v", err)
		}
		got.name, _ = req["name"].(string)
		got.stream, _ = req["stream"].(bool)
		w.Header().Set("Content-Type", "application/x-ndjson")
		io.WriteString(w, pullStream)
	}))

	var events []PullProgress
	if err := c.Pull(context.Background(), "qwen3:0.6b", func(p PullProgress) {
		events = append(events, p)
	}); err != nil {
		t.Fatalf("Pull: %v", err)
	}
	if got.name != "qwen3:0.6b" || !got.stream {
		t.Errorf("request = name %q stream %v, want qwen3:0.6b stream=true", got.name, got.stream)
	}
	if len(events) != 6 {
		t.Fatalf("got %d events, want 6: %+v", len(events), events)
	}
	if events[0].Status != "pulling manifest" || events[4].Status != "writing manifest" || events[5].Status != "success" {
		t.Errorf("unexpected phase sequence: %q", events)
	}
	if events[1].Digest != "sha256:7f4030143c1c477224c5434f8272c662a8b042079a0a584f0a27a1684fe2e1fa" ||
		events[1].Total != 522640096 || events[1].Completed != 0 {
		t.Errorf("unexpected layer event: %+v", events[1])
	}
	if events[2].Completed != 522640096 {
		t.Errorf("completed = %d, want layer size", events[2].Completed)
	}
	// Phase lines carry no digest/totals.
	if events[0].Digest != "" || events[0].Total != 0 {
		t.Errorf("manifest phase should have no layer fields: %+v", events[0])
	}
}

func TestPullInbandError(t *testing.T) {
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/x-ndjson")
		io.WriteString(w, `{"status":"pulling manifest"}`+"\n"+`{"error":"pull model manifest: file does not exist"}`+"\n")
	}))

	calls := 0
	err := c.Pull(context.Background(), "nope", func(PullProgress) { calls++ })
	if err == nil {
		t.Fatal("want error, got nil")
	}
	if !strings.Contains(err.Error(), "pull model manifest: file does not exist") {
		t.Errorf("error = %v, want surfaced in-band API message", err)
	}
	if calls != 1 {
		t.Errorf("onProgress called %d times, want 1 (manifest line only)", calls)
	}
}

func TestPullEmptyNameRejected(t *testing.T) {
	c := New("http://localhost:11434", "")
	if err := c.Pull(context.Background(), "", nil); err == nil {
		t.Fatal("Pull with empty name: want error, got nil")
	}
}

func TestPullSendsBearerToken(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuth = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/x-ndjson")
		io.WriteString(w, pullStream)
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "sekrit")
	if err := c.Pull(context.Background(), "qwen3:0.6b", nil); err != nil {
		t.Fatalf("Pull: %v", err)
	}
	if gotAuth != "Bearer sekrit" {
		t.Errorf("Authorization = %q, want %q", gotAuth, "Bearer sekrit")
	}
}

// --- M6: auth/TLS acceptance (public-CA https + bearer token) -------------
//
// The client takes the host verbatim, so an https:// base URL exercises Go's
// real TLS stack: certificate verification against the system roots (or an
// explicitly trusted pool in tests) plus the Authorization header on every
// endpoint. tlsClient trusts only the test server's certificate and disables
// the proxy env so the handshake is deterministic.
func tlsClient(t *testing.T, srv *httptest.Server, token string) *Client {
	t.Helper()
	pool := x509.NewCertPool()
	pool.AddCert(srv.Certificate())
	tlsCfg := &tls.Config{RootCAs: pool}
	c := New(srv.URL, token)
	c.http.Transport = &http.Transport{TLSClientConfig: tlsCfg, Proxy: nil}
	c.stream.Transport = &http.Transport{TLSClientConfig: tlsCfg, Proxy: nil}
	return c
}

// TestHTTPSVerifiedAndBearerSent: over a real TLS handshake (https:// host
// whose certificate the client explicitly trusts), the bearer token must be
// sent on both a JSON endpoint (List, through the timeout client) and a
// streaming endpoint (Pull, through the no-timeout stream client).
func TestHTTPSVerifiedAndBearerSent(t *testing.T) {
	saw := struct{ auth, path string }{}
	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		saw.auth = r.Header.Get("Authorization")
		saw.path = r.URL.Path
		switch r.URL.Path {
		case "/api/pull":
			w.Header().Set("Content-Type", "application/x-ndjson")
			io.WriteString(w, pullStream)
		case "/api/tags":
			w.Write([]byte(`{"models":[]}`))
		default:
			http.Error(w, "unexpected path", http.StatusNotFound)
		}
	}))
	t.Cleanup(srv.Close)

	c := tlsClient(t, srv, "tok-https")

	if _, err := c.List(context.Background()); err != nil {
		t.Fatalf("List over https: %v", err)
	}
	if saw.auth != "Bearer tok-https" {
		t.Errorf("List Authorization = %q, want %q", saw.auth, "Bearer tok-https")
	}
	if saw.path != "/api/tags" {
		t.Errorf("List path = %q", saw.path)
	}

	var events []PullProgress
	if err := c.Pull(context.Background(), "qwen3:0.6b", func(p PullProgress) {
		events = append(events, p)
	}); err != nil {
		t.Fatalf("Pull over https: %v", err)
	}
	if saw.auth != "Bearer tok-https" {
		t.Errorf("Pull Authorization = %q, want %q", saw.auth, "Bearer tok-https")
	}
	if len(events) != 6 {
		t.Errorf("Pull got %d events over https, want 6", len(events))
	}
}

// TestHTTPSUntrustedCertRejected: TLS verification is genuinely on — a host
// with a certificate the client does not trust (the self-signed httptest
// cert, with the default system roots) must fail with a certificate error,
// never a silent downgrade or a hang.
func TestHTTPSUntrustedCertRejected(t *testing.T) {
	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`{"models":[]}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "") // default transports: system roots only
	c.http.Transport = &http.Transport{Proxy: nil}

	_, err := c.List(context.Background())
	if err == nil {
		t.Fatal("List against an untrusted https host: want certificate error, got nil")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "certificate") {
		t.Errorf("error = %v, want a TLS certificate verification error", err)
	}
}

func TestPullContextCancelled(t *testing.T) {
	// The server streams one line then stalls until the client disconnects.
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/x-ndjson")
		io.WriteString(w, `{"status":"pulling manifest"}`+"\n")
		if f, ok := w.(http.Flusher); ok {
			f.Flush()
		}
		<-r.Context().Done()
	}))

	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() { done <- c.Pull(ctx, "big-model", nil) }()

	time.Sleep(20 * time.Millisecond)
	cancel()

	select {
	case err := <-done:
		if err == nil {
			t.Fatal("want cancellation error, got nil")
		}
	case <-time.After(3 * time.Second):
		t.Fatal("Pull did not return after context cancellation")
	}
}
