package ollama

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// testServer spins up a fake Ollama and returns a client pointed at it.
func testServer(t *testing.T, h http.Handler) (*Client, *httptest.Server) {
	t.Helper()
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)
	return New(srv.URL, ""), srv
}

const tagsBody = `{
  "models": [
    {
      "name": "qwen3:8b",
      "model": "qwen3:8b",
      "modified_at": "2026-09-03T08:00:00.123456789Z",
      "size": 5150000000,
      "digest": "sha256:abc",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "qwen3",
        "families": ["qwen3"],
        "parameter_size": "8.2B",
        "quantization_level": "Q4_K_M"
      }
    },
    {
      "name": "gemma3:12b",
      "model": "gemma3:12b",
      "modified_at": "2026-08-01T01:02:03Z",
      "size": 8123456789,
      "digest": "sha256:def",
      "details": {
        "parent_model": "gemma3:4b",
        "format": "gguf",
        "family": "gemma3",
        "families": ["gemma3"],
        "parameter_size": "12B",
        "quantization_level": "Q4_K_M"
      }
    }
  ]
}`

func TestListParsesModels(t *testing.T) {
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/api/tags" {
			t.Errorf("got %s %s, want GET /api/tags", r.Method, r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(tagsBody))
	}))

	models, err := c.List(context.Background())
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(models) != 2 {
		t.Fatalf("len = %d, want 2", len(models))
	}

	q := models[0]
	if q.Name != "qwen3:8b" || q.Family != "qwen3" ||
		q.ParameterSize != "8.2B" || q.Quantization != "Q4_K_M" ||
		q.SizeBytes != 5150000000 {
		t.Errorf("unexpected first model: %+v", q)
	}
	wantMod := time.Date(2026, 9, 3, 8, 0, 0, 123456789, time.UTC)
	if !q.ModifiedAt.Equal(wantMod) {
		t.Errorf("ModifiedAt = %v, want %v", q.ModifiedAt, wantMod)
	}

	g := models[1]
	if g.Family != "gemma3" || g.ParameterSize != "12B" {
		t.Errorf("unexpected second model: %+v", g)
	}
}

func TestListSendsBearerToken(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuth = r.Header.Get("Authorization")
		w.Write([]byte(`{"models":[]}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "sekrit")
	if _, err := c.List(context.Background()); err != nil {
		t.Fatalf("List: %v", err)
	}
	if gotAuth != "Bearer sekrit" {
		t.Errorf("Authorization = %q, want %q", gotAuth, "Bearer sekrit")
	}
}

func TestListNoTokenNoHeader(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuth = r.Header.Get("Authorization")
		w.Write([]byte(`{"models":[]}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	if _, err := c.List(context.Background()); err != nil {
		t.Fatalf("List: %v", err)
	}
	if gotAuth != "" {
		t.Errorf("Authorization = %q, want empty", gotAuth)
	}
}

const showBody = `{
  "license": "Apache-2.0",
  "modelfile": "# Modelfile generated by ollama show\nFROM qwen3:8b",
  "parameters": "stop \"<|im_end|>\"\ntemperature 0.7",
  "template": "{{ .Prompt }}",
  "details": {
    "parent_model": "",
    "format": "gguf",
    "family": "qwen3",
    "families": ["qwen3"],
    "parameter_size": "8.2B",
    "quantization_level": "Q4_K_M"
  },
  "model_info": {
    "general.architecture": "qwen3",
    "general.parameter_count": 8240000000,
    "general.file_type": 15
  },
  "projector_info": {},
  "capabilities": ["completion", "tools"]
}`

func TestShowPostsNameAndParses(t *testing.T) {
	var gotBody string
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/api/show" {
			t.Errorf("got %s %s, want POST /api/show", r.Method, r.URL.Path)
		}
		var req map[string]string
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			t.Errorf("decode request: %v", err)
		}
		gotBody = req["name"]
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(showBody))
	}))

	d, err := c.Show(context.Background(), "qwen3:8b")
	if err != nil {
		t.Fatalf("Show: %v", err)
	}
	if gotBody != "qwen3:8b" {
		t.Errorf("request name = %q, want qwen3:8b", gotBody)
	}
	if d.License != "Apache-2.0" || d.Details.ParameterSize != "8.2B" {
		t.Errorf("unexpected details: %+v", d)
	}
	if len(d.Capabilities) != 2 || d.Capabilities[0] != "completion" {
		t.Errorf("capabilities = %v", d.Capabilities)
	}
	count, ok := d.ModelInfo["general.parameter_count"].(float64)
	if !ok || count != 8240000000 {
		t.Errorf("model_info.parameter_count = %v, want 8240000000", d.ModelInfo["general.parameter_count"])
	}
	if !strings.Contains(d.Modelfile, "FROM qwen3:8b") {
		t.Errorf("modelfile = %q", d.Modelfile)
	}
}

func TestShowEmptyNameRejected(t *testing.T) {
	c := New("http://localhost:11434", "")
	if _, err := c.Show(context.Background(), ""); err == nil {
		t.Fatal("Show with empty name: want error, got nil")
	}
}

func TestAPIErrorBodySurfaced(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(`{"error":"model 'nothere' not found"}`))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	_, err := c.Show(context.Background(), "nothere")
	if err == nil {
		t.Fatal("want error, got nil")
	}
	if !strings.Contains(err.Error(), "model 'nothere' not found") {
		t.Errorf("error = %v, want surfaced API message", err)
	}
}

func TestHTTPStatusWithoutJSONError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte("Not Found"))
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	if _, err := c.List(context.Background()); err == nil {
		t.Fatal("want error, got nil")
	} else if !strings.Contains(err.Error(), "404") {
		t.Errorf("error = %v, want HTTP status in message", err)
	}
}

func TestConnectionRefused(t *testing.T) {
	// A closed listener gives a guaranteed-refused address.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	addr := srv.URL
	srv.Close()

	c := New(addr, "")
	if _, err := c.List(context.Background()); err == nil {
		t.Fatal("want error for refused connection, got nil")
	}
}

func TestRequestTimeout(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(200 * time.Millisecond)
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	c.http.Timeout = 20 * time.Millisecond
	start := time.Now()
	if _, err := c.List(context.Background()); err == nil {
		t.Fatal("want timeout error, got nil")
	}
	if time.Since(start) > 250*time.Millisecond {
		t.Errorf("timeout took %v, want fast failure", time.Since(start))
	}
}

func TestContextCancelled(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		<-r.Context().Done()
	}))
	t.Cleanup(srv.Close)

	c := New(srv.URL, "")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := c.List(ctx); err == nil {
		t.Fatal("want cancelled-context error, got nil")
	}
}

func TestHostTrailingSlashNormalized(t *testing.T) {
	var path string
	c, _ := testServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path = r.URL.Path
		w.Write([]byte(`{"models":[]}`))
	}))
	// Point a second client at the same host with trailing slashes.
	c2 := New(c.baseURL+"/", "")
	if _, err := c2.List(context.Background()); err != nil {
		t.Fatalf("List: %v", err)
	}
	if path != "/api/tags" {
		t.Errorf("path = %q, want /api/tags (no double slash)", path)
	}
}
